[package]
name = "prevent_sleep"
version = "0.1.1"
edition = "2021"
authors = ["Stefano Probst <me@stefano-probst.dev>"]

[dependencies]
ctrlc = "3.4.5"
windows = { version = "0.58.0", features = ["Win32_System_Power"] }

[profile.release]
lto = true
codegen-units = 1